### ISSUE TITLE
Define a config file

### ISSUE THREAD

**Issue by enko** [tmolitor-stud-tu/simple-dnssec#3]
At the moment the config file resides in /srv/common and is loosly defined through the code. The config file should reside in `/etc`. 

I would propose `/etc/simple-dnssec/common.conf`. We should provide a fully commented config file for people who do not want to use the installer or want to learn in detail what the config variables are doing.

**Comment by tmolitor-stud-tu** [comment]
the config file is added and every option is briefly commented.
